package com.tcs.assignment.policymaker.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.UUID;

@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@DynamoDBTable(tableName = "policies")
public class Policy {
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private UUID id;

    @NotBlank(message = "Policy name is mandatory")
    @DynamoDBRangeKey(attributeName = "name")
    private String name;

    @NotNull(message = "Policy amount is mandatory")
    @DynamoDBAttribute(attributeName = "amount")
    private Double amount;
}
